# Secrets created and maintained on the GCVE community owned project.
# Also see docs at infra/gcp/terraform/k8s-infra-gcp-gcve/README.md
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: k8s-gcp-gcve-ci
spec:
  backendType: gcpSecretsManager
  projectId: broadcom-451918
  data:
  - key: k8s-gcp-gcve-ci-url
    name: k8s-gcp-gcve-ci-url
    version: latest
  - key: k8s-gcp-gcve-ci-username
    name: k8s-gcp-gcve-ci-username
    version: latest
  - key: k8s-gcp-gcve-ci-password
    name: k8s-gcp-gcve-ci-password
    version: latest
  - key: k8s-gcp-gcve-ci-thumbprint
    name: k8s-gcp-gcve-ci-thumbprint
    version: latest
